steps:
- uses: actions/checkout@v2

- name: Configure AWS credentials
  uses: aws-actions/configure-aws-credentials@v2
  with:
    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}        # ดึงจาก Production Environment Secrets
    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # ดึงจาก Production Environment Secrets
    aws-region: us-east-1                                      # เปลี่ยนเป็น region ที่ใช้งาน

- name: Login to Amazon ECR
  run: |
    aws ecr get-login-password --region us-east-1 \
      | docker login --username AWS --password-stdin 863518417758.dkr.ecr.us-east-1.amazonaws.com

- name: Build and Push Docker image
  run: |
    docker build -t mobile-lpr/backend .
    docker tag mobile-lpr/backend:latest 863518417758.dkr.ecr.us-east-1.amazonaws.com/mobile-lpr/backend:latest
    docker push 863518417758.dkr.ecr.us-east-1.amazonaws.com/mobile-lpr/backend:latest

- name: Verify AWS credentials
  run: |
    aws sts get-caller-identity  # ตรวจสอบว่า AWS credentials ถูกต้องและเชื่อมต่อกับ AWS ได้
    echo "AWS credentials are valid"

- name: Deploy to ECS
  run: |
    aws ecs update-service \
      --cluster my-cluster \
      --service my-service \
      --force-new-deployment \
      --region us-east-1        # ใช้ region เดียวกับ ECR